### ISSUE TITLE
Cannot download the App

### ISSUE THREAD

**Issue by bearpaw** [Quest2ROS/quest2ros#5]
![IMG_0411](https://github.com/user-attachments/assets/ece9952a-f564-46d1-8a19-43868710aefe)

Thanks for the app. However I am not able to download the app. Any help would be greatly appreciated!

**Comment by haoshuiwuxiang** [comment]
Can you install it now? When I entered this page, I couldn't find how to download this app
![image](https://github.com/user-attachments/assets/3f55d030-759e-48ca-bcd7-f90b26078056)

**Comment by bearpaw** [comment]
Yes. I can download it after the author refreshed the alpha access:
https://www.meta.com/s/1stEAnW1u

But I forgot how I downloaded it. Can you find the app on your Quest headset (not from a PC web browser)?

**Comment by haoshuiwuxiang** [comment]
> Yes. I can download it after the author refreshed the alpha access: https://www.meta.com/s/1stEAnW1u
> 
> But I forgot how I downloaded it. Can you find the app on your Quest headset (not from a PC web browser)?

Yes, I have successfully installed this app

**Comment by sudarshan-s-harithas** [comment]
Hi, 
Thank you for the great work. I am unable to download it and it returns an error message shown below. 

I tried this https://www.meta.com/s/1stEAnW1u and the link given in the webpage, but none seems to work. 

![Screenshot from 2024-11-10 16-32-38](https://github.com/user-attachments/assets/e6894980-ee05-4ffb-b276-dd338757e71a)
